{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "radar.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radar.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "radar.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
